--ASSIGNMENT 3--

USE HANON;

--CREATING THE PREVIOUS TABLE WITH SOME CONSTRAINTS--

SELECT * FROM INP;
SELECT * FROM INP_SAL;

-- ADDING PRIMARY KEY CONSTRAINT--
ALTER TABLE INP
ALTER COLUMN EID CHAR(7) NOT NULL;
ALTER TABLE INP
ADD CONSTRAINT PKID PRIMARY KEY (EID);

--ADDING NOT NULL CONSTRAINT--
ALTER TABLE INP
ALTER COLUMN NAME VARCHAR(20) NOT NULL;

--ADDING CHECK CONSTRAINT--
ALTER TABLE INP
ADD CONSTRAINT CKAD CHECK(ADDR NOT LIKE 'UTTAM NAGAR');

ALTER TABLE INP
ADD CONSTRAINT CKCY CHECK(CITY IN ('CHENNAI','M M NAGAR','S.P KOVIL','MUDUCHUR','RETTERY',
                                                    'ANAGAPUTHUR','AMBATTUR','TAMBARAM','URAPAKKAM','SRM NAGAR','CHROMPET','MM NAGAR'));

ALTER TABLE INP
ADD CONSTRAINT CKED CHECK(EMAIL LIKE '%GMAIL%' OR EMAIL LIKE '%YAHOO%');

ALTER TABLE INP
ADD CONSTRAINT CKDB CHECK(DOB>='01-01-1950');

--ADDING UNIQUE CONSTRAINT--
ALTER TABLE INP
ADD CONSTRAINT UQPH UNIQUE (PHONE);

SELECT * FROM INP;

--------------------------------------------------------------------

--ADDING CONSTRAINT TO INP_SAL TABLE--

SELECT * FROM INP_SAL;

--FOREIGN KEY CONSTRAINT--
ALTER TABLE INP_SAL
ADD CONSTRAINT FKED FOREIGN KEY(EID) REFERENCES INP(EID);

ALTER TABLE INP_SAL
ADD CONSTRAINT CKDP CHECK (DEPT IN ('HVAC','FG','INP QUALITY','IQ QUALITY','FT','COND','COMP','DOCK AUDIT','MFG','QUALITY'));

ALTER TABLE INP_SAL
ADD CONSTRAINT CKDE CHECK(DESI IN ('SR ENGINEER','DEP ENGINEER','ASS MANAGER','EMPLOYEE',
                                                   'DEP G MANAGER','GENERALMANAGER','DEP MANAGER','MANAGER'));

ALTER TABLE INP_SAL
ADD CONSTRAINT CKSL CHECK (SALARY >=20000);

--ADDING DEFAULT CONSTRAINT--
ALTER TABLE INP_SAL
ADD CONSTRAINT DFDP DEFAULT 'MANAGER' FOR DEPT;






