---ASSIGNMENT 7---

USE HANON;

SELECT * FROM INP;
SELECT * FROM INP_SAL;


--A-1:-
SELECT INP.EID,NAME,CITY FROM INP
WHERE CITY='M M NAGAR';

--A-2:-
SELECT INP.EID,NAME,DOJ,DEPT,DESI,SALARY FROM INP
INNER JOIN INP_SAL
ON INP.EID=INP_SAL.EID
WHERE DESI LIKE '%MANAGER%';


--A-3:-
SELECT INP.EID,NAME,CITY,SALARY FROM INP
INNER JOIN INP_SAL
ON INP.EID=INP_SAL.EID
WHERE CITY LIKE '%NAGAR%';

UPDATE INP_SAL SET SALARY= SALARY/SALARY*0.1
WHERE EID IN (SELECT EID FROM INP WHERE CITY LIKE '%NAGAR%');

--A-4:-
SELECT INP.EID,NAME,CITY,DOJ,DEPT,DESI,SALARY FROM INP
INNER JOIN INP_SAL
ON INP.EID=INP_SAL.EID
WHERE NAME LIKE 'RANJITH%' AND NAME LIKE '%MUSTHAFA%' ;

--A-5:-
CREATE TABLE TRAINING
(EID CHAR(7),NAME VARCHAR(20),DEPT VARCHAR(18));

SELECT INP.EID,NAME,DEPT FROM INP
INNER JOIN INP_SAL
ON INP.EID=INP_SAL.EID
WHERE DEPT LIKE '%QUALITY';

INSERT INTO TRAINING(EID,NAME,DEPT)
(SELECT INP.EID,NAME,DEPT FROM INP
INNER JOIN INP_SAL
ON INP.EID=INP_SAL.EID
WHERE DEPT LIKE '%QUALITY');

--A-6:-
DELETE FROM TRAINING
WHERE EID IN (SELECT EID FROM INP_SAL WHERE DESI = 'GENERALMANAGER');

SELECT * FROM TRAINING;

--A-7:-
SELECT * FROM INP_SAL
WHERE EXISTS (SELECT * FROM INP_SAL WHERE SALARY>200000);



































