---ASSINGMENT 5---

USE HANON;

SELECT * FROM INP;
SELECT * FROM INP_SAL;

--EID NAME CITY DOJ DEPT DESI SALARY OF DELHI EMPLOYEES--

SELECT INP.EID,NAME,CITY,DOJ,DEPT,DESI,SALARY FROM INP
INNER JOIN INP_SAL
ON INP.EID=INP_SAL.EID
WHERE CITY='M M NAGAR';

--DETAILS OF THE EMPLOYEES WHOSE SALARY DETAILS ARE NOT AVAILABLE--

SELECT INP.EID,NAME,CITY,DOJ,DEPT,DESI,SALARY FROM INP
FULL JOIN INP_SAL
ON INP.EID=INP_SAL.EID
WHERE SALARY= NULL;

------------------INVENTORY---------------------






