USE HANON;

---ASSINGMENT-7.1--

---USER DEFINED FUNCTION---

--EXAMPLE FOR SCALAR FUNCTION--

CREATE FUNCTION CAL (@X AS INT,@Y AS INT,@R AS CHAR(1))
RETURNS INT
AS
BEGIN
         
		 DECLARE @N INT;
		 IF @R = '+'
		   SET @N= @X + @Y;
         ELSE IF @R = '-'
		   SET @N= @X - @Y;
		 ELSE IF @R = '*'
		   SET @N = @X * @Y;
		 ELSE IF @R = '%'
		   SET @N = @X % @Y;
		 ELSE IF @R = '/'
		   SET @N = @X/@Y;
		 ELSE 
		   SET @N = 0;
		 RETURN @N;
END;


SELECT dbo.CAL(40,20,'-')AS 'RESULTS';

--EXAMPLE FOR TABLE FUNCTION---

CREATE FUNCTION SAL_DEL (@X AS VARCHAR(25),@Y AS VARCHAR(25))
RETURNS TABLE
AS
RETURN(SELECT INP.EID,NAME,CITY,DEPT,DESI,SALARY AS 'BASIC',SALARY *.15 AS 'HRA',SALARY *.09 AS 'PF' 
       FROM INP
	   INNER JOIN INP_SAL
	   ON INP.EID=INP_SAL.EID
	   WHERE DEPT=@X AND DESI=@Y);

SELECT * FROM dbo.SAL_DEL('INP QUALITY','DEP MANAGER');








